version: '2'
services:
    wwwserver:
       build: .
       image: dasn/phpciwebapp 
       environment:
            PORT: 80 
       ports:
            - "8080:80"
       volumes:
            - ./html:/var/www/html

